import type { ColorToken, DesignScan } from '@specimen/core/schema';

const tok = (id: string, hex: string, weight: number, usage: ColorToken['usage']): ColorToken => ({
  id,
  hex,
  oklch: [0.5, 0.1, 270],
  alpha: 1,
  weight,
  usage,
});

/** Plausible Linear-like scan for visual development (`sidepanel.html?demo=1`). */
export const sampleScan: DesignScan = {
  schemaVersion: 2,
  id: 'demo',
  url: 'https://linear.app/',
  host: 'linear.app',
  title: 'Linear',
  scannedAt: Date.now(),
  viewport: { w: 1440, h: 900 },
  colorScheme: 'dark',
  colors: {
    palette: [
      tok('c1', '#08090a', 0.46, { bg: 0.9, text: 0, border: 0, fill: 0.1 }),
      tok('c2', '#f7f8f8', 0.14, { bg: 0, text: 0.95, border: 0, fill: 0.05 }),
      tok('c3', '#8a8f98', 0.1, { bg: 0, text: 0.9, border: 0.05, fill: 0.05 }),
      tok('c4', '#5e6ad2', 0.07, { bg: 0.4, text: 0.1, border: 0, fill: 0.5 }),
      tok('c5', '#141516', 0.08, { bg: 0.95, text: 0, border: 0.05, fill: 0 }),
      tok('c6', '#23252a', 0.05, { bg: 0.2, text: 0, border: 0.8, fill: 0 }),
      tok('c7', '#d0d6e0', 0.04, { bg: 0, text: 1, border: 0, fill: 0 }),
      tok('c8', '#7170ff', 0.03, { bg: 0.1, text: 0.6, border: 0, fill: 0.3 }),
      tok('c9', '#4cb782', 0.01, { bg: 0.2, text: 0.3, border: 0, fill: 0.5 }),
      tok('c10', '#eb5757', 0.01, { bg: 0.2, text: 0.3, border: 0, fill: 0.5 }),
    ],
    roles: {
      background: 'c1',
      surface: 'c5',
      border: 'c6',
      textPrimary: 'c2',
      textSecondary: 'c7',
      textMuted: 'c3',
      accent: 'c4',
      accentHover: 'c8',
      link: 'c8',
      success: 'c9',
      danger: 'c10',
    },
    gradients: [],
  },
  typography: {
    families: [
      {
        id: 'f1',
        name: 'Inter Variable',
        stack: '"Inter Variable", "SF Pro Display", -apple-system, system-ui, sans-serif',
        role: 'display',
        source: 'self-hosted',
        weights: [400, 510, 590],
      },
      {
        id: 'f2',
        name: 'Berkeley Mono',
        stack: '"Berkeley Mono", ui-monospace, "SF Mono", Menlo, monospace',
        role: 'mono',
        source: 'self-hosted',
        weights: [400],
      },
    ],
    styles: [
      {
        id: 's1',
        role: 'display',
        familyId: 'f1',
        size: 64,
        weight: 590,
        lineHeight: 1.06,
        letterSpacingEm: -0.022,
        weightShare: 0.03,
        sample: 'Plan and build products',
      },
      {
        id: 's2',
        role: 'h2',
        familyId: 'f1',
        size: 40,
        weight: 590,
        lineHeight: 1.1,
        letterSpacingEm: -0.02,
        weightShare: 0.06,
        sample: 'Made for modern teams',
      },
      {
        id: 's3',
        role: 'h3',
        familyId: 'f1',
        size: 24,
        weight: 510,
        lineHeight: 1.33,
        letterSpacingEm: -0.012,
        weightShare: 0.1,
        sample: 'Streamlined workflows',
      },
      {
        id: 's4',
        role: 'body',
        familyId: 'f1',
        size: 16,
        weight: 400,
        lineHeight: 1.5,
        letterSpacingEm: 0,
        weightShare: 0.5,
        sample: 'Purpose-built for planning and building.',
      },
      {
        id: 's5',
        role: 'small',
        familyId: 'f1',
        size: 13,
        weight: 400,
        lineHeight: 1.5,
        letterSpacingEm: 0,
        weightShare: 0.2,
        sample: 'Updated 2 hours ago',
      },
      {
        id: 's6',
        role: 'code',
        familyId: 'f2',
        size: 12,
        weight: 400,
        lineHeight: 1.5,
        letterSpacingEm: 0,
        weightShare: 0.04,
        sample: 'LIN-1234',
      },
    ],
    baseSize: 16,
    scaleRatio: 1.5,
  },
  spacing: {
    baseUnit: 4,
    scale: [4, 8, 12, 16, 24, 32, 48, 64, 96],
    sectionPaddingY: 96,
    contentGap: 24,
  },
  radii: {
    scale: [
      { value: 4, weight: 0.3 },
      { value: 6, weight: 0.4 },
      { value: 12, weight: 0.2 },
      { value: 9999, weight: 0.1 },
    ],
    button: 6,
    card: 12,
    input: 6,
    pillButtons: false,
  },
  shadows: [
    { css: '0 1px 2px rgba(0,0,0,0.3)', weight: 0.5, level: 1 },
    { css: '0 4px 24px rgba(0,0,0,0.4)', weight: 0.3, level: 2 },
    { css: '0 24px 64px -12px rgba(0,0,0,0.6)', weight: 0.2, level: 3 },
  ],
  borders: [
    { width: 1, colorRole: 'border', weight: 0.9 },
    { width: 2, colorRole: 'accent', weight: 0.1 },
  ],
  layout: {
    containerMaxWidth: 1200,
    gutter: 24,
    breakpoints: [640, 768, 1024, 1280],
    density: 'airy',
    blueprint: [
      {
        index: 0,
        kind: 'nav',
        y: 0,
        height: 64,
        arrangement: 'split',
        columns: 3,
        align: 'left',
        confidence: 0.95,
      },
      {
        index: 1,
        kind: 'hero',
        y: 64,
        height: 820,
        arrangement: 'stack',
        columns: 1,
        align: 'center',
        confidence: 0.9,
      },
      {
        index: 2,
        kind: 'logos',
        y: 884,
        height: 160,
        arrangement: 'list',
        columns: 6,
        align: 'center',
        confidence: 0.7,
      },
      {
        index: 3,
        kind: 'features',
        y: 1044,
        height: 1400,
        arrangement: 'bento',
        columns: 3,
        align: 'left',
        confidence: 0.8,
      },
      {
        index: 4,
        kind: 'testimonials',
        y: 2444,
        height: 600,
        arrangement: 'grid',
        columns: 3,
        align: 'left',
        confidence: 0.6,
      },
      {
        index: 5,
        kind: 'cta',
        y: 3044,
        height: 400,
        arrangement: 'stack',
        columns: 1,
        align: 'center',
        confidence: 0.75,
      },
      {
        index: 6,
        kind: 'footer',
        y: 3444,
        height: 400,
        arrangement: 'grid',
        columns: 5,
        align: 'left',
        confidence: 0.9,
      },
    ],
  },
  cssVariables: {},
  meta: {
    extractorVersion: 'demo',
    sampleCount: 1824,
    durationMs: 180,
    warnings: ['cross-origin stylesheet skipped'],
  },
};
