/** Computed-style keys sampled per element (ARCHITECTURE §4.1). */
export const STYLE_KEYS = [
  'color',
  'backgroundColor',
  'backgroundImage',
  'borderTopColor',
  'borderTopWidth',
  'borderTopStyle',
  'borderRightColor',
  'borderRightWidth',
  'borderRightStyle',
  'borderBottomColor',
  'borderBottomWidth',
  'borderBottomStyle',
  'borderLeftColor',
  'borderLeftWidth',
  'borderLeftStyle',
  'borderRadius',
  'boxShadow',
  'fontFamily',
  'fontSize',
  'fontWeight',
  'lineHeight',
  'letterSpacing',
  'textTransform',
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'marginTop',
  'marginRight',
  'marginBottom',
  'marginLeft',
  'gap',
  'rowGap',
  'columnGap',
  'display',
  'flexDirection',
  'gridTemplateColumns',
  'justifyContent',
  'alignItems',
  'maxWidth',
  'width',
  'position',
  'opacity',
  'transitionDuration',
  'transitionTimingFunction',
] as const;

export type StyleKey = (typeof STYLE_KEYS)[number];
