// Usage: pnpm fixtures:summary
// Runs extract() over fixtures/raw/*.json and writes a compact human-readable
// fixtures/raw/SUMMARY.md for sanity review.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { extract, RawPageSchema } from '../packages/core/src';

const root = fileURLToPath(new URL('..', import.meta.url));
const dir = join(root, 'fixtures/raw');
const files = readdirSync(dir)
  .filter((f) => f.endsWith('.json'))
  .sort();
const out: string[] = [
  '# Real-site scan summary',
  '',
  'Generated by `pnpm fixtures:summary`. Do not edit.',
  '',
];

for (const f of files) {
  const raw = RawPageSchema.parse(JSON.parse(readFileSync(join(dir, f), 'utf8')));
  const scan = extract(raw);
  const tok = new Map(scan.colors.palette.map((t) => [t.id, t]));
  const roles = Object.entries(scan.colors.roles)
    .map(
      ([r, id]) =>
        `${r} ${tok.get(id as string)?.hex}${tok.get(id as string)?.sourceVar ? ` (${tok.get(id as string)?.sourceVar})` : ''}`,
    )
    .join(', ');
  const ty = (r: string) => scan.typography.styles.find((s) => s.role === r);
  const fmt = (r: string) => {
    const s = ty(r);
    return s ? `${s.size}px/${s.weight}/lh ${s.lineHeight}` : 'n/a';
  };
  out.push(`## ${f.replace('.json', '')} (${scan.host})`);
  out.push(
    `- samples ${scan.meta.sampleCount}, extract ${scan.meta.durationMs} ms, warnings ${scan.meta.warnings.length}`,
  );
  out.push(`- palette ${scan.colors.palette.length} tokens; roles: ${roles || 'none'}`);
  out.push(
    `- type: body ${fmt('body')}, h1 ${fmt('h1')}, h2 ${fmt('h2')}; base ${scan.typography.baseSize}; ratio ${scan.typography.scaleRatio ?? 'null'}`,
  );
  out.push(
    `- families: ${scan.typography.families.map((x) => `${x.name} [${x.role}, ${x.source}]`).join('; ')}`,
  );
  out.push(
    `- spacing: base ${scan.spacing.baseUnit}, scale ${scan.spacing.scale.join('/')}, sectionPadY ${scan.spacing.sectionPaddingY}, gap ${scan.spacing.contentGap}`,
  );
  out.push(
    `- radii: button ${scan.radii.button ?? '-'}, card ${scan.radii.card ?? '-'}, input ${scan.radii.input ?? '-'}, pill ${scan.radii.pillButtons}; shadows ${scan.shadows.length}`,
  );
  out.push(
    `- layout: container ${scan.layout.containerMaxWidth ?? 'null'}, gutter ${scan.layout.gutter ?? 'null'}, breakpoints ${scan.layout.breakpoints.join('/')}, density ${scan.layout.density}`,
  );
  out.push(
    `- sections (${scan.layout.blueprint.length}): ${scan.layout.blueprint.map((s) => `${s.kind}${s.confidence < 0.2 ? '?' : ''}`).join(' > ')}`,
  );
  out.push('');
}
writeFileSync(join(dir, 'SUMMARY.md'), `${out.join('\n')}\n`);
console.log(`wrote fixtures/raw/SUMMARY.md (${files.length} sites)`);
